- name: wifi file permission
  file: path=/etc/wpa_supplicant/wpa_supplicant.conf mode="g+w,o+w"
- name: update repo
  apt:
    update_cache: yes
    cache_valid_time: 36000
  tags:
    - repo
- name: install vlc
  apt:
    name: vlc
- name: install usbmount
  apt:
    name: usbmount
- name: copy alsa usb sound driver conf
  copy: src=files/alsa_usb.conf dest=/usr/share/alsa/alsa.conf.d/
  tags:
    - usbaudio
- name: copy agent
  copy: src=../agent/fangge-agent.py dest=/usr/local/bin/ mode="u+rwx,g+rx,o+rx"
  tags:
    - agent
- name: enable agent on boot clean
  replace: dest=/etc/rc.local regexp='^runuser.*' 
  tags:
    - agent
- name: enable agent on boot
  replace: dest=/etc/rc.local regexp='^exit 0' replace='runuser -l pi -c \'fangge-agent.py --usb --url "{{ AGENT_URL }}" --id {{ AGENT_ID }} --token {{ AGENT_TOKEN }} --path {{ MUSIC_FOLDER }} --info "{{ AGENT_INFO }}"\'\nexit 0' backup=yes
  tags:
    - agent
- name: mkdir music data
  file: path={{ MUSIC_FOLDER }} state=directory mode="u+rw,g+rwx,o+rwx"
  become: no
  tags:
    - agent
- name: copy sample media
  copy: src=../agent/music/ dest={{ MUSIC_FOLDER }}
  become: no
  tags:
    - agent
- name: mkdir cmd voices folder
  file: path={{ VOICE_FOLDER }} state=directory
  become: no
  tags:
    - agent
- name: copy voice cmd
  copy: src=../agent/voices/ dest={{ VOICE_FOLDER }}
  become: no
  tags:
    - agent
- name: load music
  copy: src={{ MUSIC_LIB }} dest={{ MUSIC_FOLDER }}
  become: no
  tags:
    - music
